### PR TITLE
Assign UID and GID

### LINKED ISSUE #9: Running rclone as different user in the container
Any suggestions for how I could change the docker user that's running rlcone inside the container.

By default it's running as root, so the files it syncs into the mounted folder come out as root:root.

If I pass in the user to the docker run command, it errors out on accessing crontab (timezone) which makes sense

```
# docker run ... --user=90:1000
INFO: Running rclone v1.50.1
INFO: Starting sync.sh pid 30 Wed Nov 13 15:38:27 UTC 2019
WARNING: Source directory is empty. Skipping move command.

/entrypoint.sh: line 80: crontab: Permission denied
```

### PR DESCRIPTION
**Pull request by mikeburgh**
Closes #9 

Not sure this is the best way to do it, and I have not tested cron yet, but wanted to get your thoughts on the approach.

### CODE REVIEW

**Comment by pfidr34** [comment]
Running this in test now and it works as expected.
Will set up for daily cron and then merge on Sunday.

**Comment by mikeburgh** [comment]
Sounds good, just fixed up two edge cases.. if people use -u=uid:group on docker command line it was going to ignore that and stay as root, and it was also not switching to a user if they already existed.

**Comment by pfidr34** [comment]
Pulled in this change and tested.
Will run on daily cron until Sunday then merge.

**Comment by pfidr34** [comment]
Will need to look at this further this weekend. Cron failed.

```
INFO: Starting crond ...,
INFO: crond started,
==> /tmp/crond.log <==,
,
==> /tmp/sync.log <==,
INFO: Starting sync.sh pid 84 Fri Nov 15 00:00:01 CST 2019,
INFO: Removing logs older than 7 day(s)...,
2019/11/15 00:00:06 Failed to save config after 10 tries: Failed to create temp file for new config: open /config/rclone.conf316178700: permission denied,
WARNING: Source directory is empty. Skipping copy command.,
```

**Comment by pfidr34** [comment]
I think what is happening is that the configs were previously owned by root so 1000:1000 couldn't write to the config dir. I have made a copy of the dir and chown'd it and rerunning the test.

Will either need to make a disclaimer in the readme or all config to still be ran by root and only worry about running rclone as the specified user.

**Comment by pfidr34** [comment]
Working all weekend on cron. Merging.

**Comment by mikeburgh** [comment]
I had a though about the perms, if it comes up, we could make the root user set read only for everyone on the config file before dropping into the other user account. I can try and have a go at that if you want later this week once I get some other things sorted ? or see what the feedback is once you release the new container ?

**Comment by pfidr34** [comment]
I'm just gonna release with a note that the UID/GID need write on the configs/logs and see what the noise is.

**Pull request merged**
